### ISSUE TITLE
go panic when using a created VariableGroup in a BuildDefinition

### ISSUE THREAD

**Issue by alastairs** [pulumi/pulumi-azuredevops#86]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We use the Azure Storage back-end for Pulumi, and Azure Key Vault as the secrets provider. As such, we need to set a few environment variables in our Azure DevOps pipelines deploying Pulumi projects: the usual `ARM_CLIENT_ID`, etc. I'm trying to define a variable group with these values, but passing the created `VariableGroup` to a `BuildDefinition` throws a go panic and causes the deployment to fail.

### Steps to reproduce

First I pull the variables for the variable group from config:
```typescript
const pulumiVariables = new pulumi.Config().requireObject<{ variables: Record<string, string>; }>('azuredevops').variables;
```

and then I map the config object to a `VariableGroup` resource.
```typescript
const pulumiVariableGroup = new azdo.VariableGroup(`pulumi`, {
    projectId: project.id,
    variables: pulumi.output(
        Object.keys(pulumiVariables).map(async k => {
            if (await pulumi.isSecret(pulumi.output(pulumiVariables[k]))) {
                return {
                    name: k,
                    isSecret: true,
                    secretValue: pulumiVariables[k]
                } as azdo.types.input.VariableGroupVariable;
            } else {
                return {
                    name: k,
                    value: pulumiVariables[k]
                } as azdo.types.input.VariableGroupVariable;
            }
        })),
    allowAccess: true,
    name: "pulumi",
    description: "Variables required for Azure DevOps pipelines to operate on Pulumi projects. Managed by Pulumi."
});
```

Finally, I parse the `id` of the created `VariableGroup` as an int to include in the `variableGroups` array:
```typescript
const pipeline = new azdo.BuildDefinition(`pipeline`, {
    projectId: project.id,
    repository: {
        ...githubRepo,
        ymlPath: "azure-pipelines.yml"
    },
    variableGroups: [pulumiVariableGroup.id.apply(id => parseInt(id).valueOf())]
});
```

Expected: Deployment completes successfully
Actual: Deployment fails with a go panic:

```plain
panic: interface conversion: interface {} is string, not int
    goroutine 89 [running]:
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.SerializeValueForHash(0xc000b7b120, 0x2138c00, 0x265c230, 0xc000af0640)
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/serialize.go:24 +0x9f9
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.HashSchema.func1(0x2138c00, 0x265c230, 0xc000380420)
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/set.go:43 +0x68
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v1.v1Schema.SetHash(0xc000af0780, 0x2138c00, 0x265c230, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfshim/sdk-v1/schema.go:176 +0x62
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.visitPropertyValue(0xc00055aaf0, 0xf, 0xc000744ae0, 0xe, 0x2115500, 0xc000a5ae28, 0x26b9bf8, 0xc000af0780, 0x0, 0xc000af0700, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/diff.go:114 +0x491
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.doIgnoreChanges(0x26acc50, 0xc00073f680, 0xc0007d02d0, 0xc0007d1440, 0xc0007d1bc0, 0x0, 0x0, 0x0, 0x26b0ed0, 0xc000f0dda0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/diff.go:259 +0x4e5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc000ab8400, 0x269f2a8, 0xc0007d13b0, 0xc0007832d0, 0xc000ab8400, 0x21c5301, 0xc00107a8c0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/provider.go:750 +0x7ab
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1(0x269f2a8, 0xc0007d13b0, 0x232e000, 0xc0007832d0, 0x233d9e0, 0x306f128, 0x269f2a8, 0xc0007d13b0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.17.0/proto/go/provider.pb.go:2584 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x269f2a8, 0xc0007d11d0, 0x232e000, 0xc0007832d0, 0xc000f0d340, 0xc000a5ab58, 0x0, 0x0, 0x2679d20, 0xc00039f3a0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler(0x238e060, 0xc000ab8400, 0x269f2a8, 0xc0007d11d0, 0xc000268f60, 0xc0007494e0, 0x269f2a8, 0xc0007d11d0, 0xc000a00f00, 0x499)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.17.0/proto/go/provider.pb.go:2586 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000324700, 0x26b18f8, 0xc000389980, 0xc000a6d440, 0xc0007d0960, 0x302b788, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc000324700, 0x26b18f8, 0xc000389980, 0xc000a6d440, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000ac9cf0, 0xc000324700, 0x26b18f8, 0xc000389980, 0xc000a6d440)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
```

I suspect (but don't know) that this provider has incorrectly defined the `variableGroups` argument as an integer when it should be a string, and the number I've parsed out to pass to the `variableGroups` argument is expecting a string instead--or it doesn't fully support the `Input<Input<number>[]>` provided. I've confirmed the `variableGroups: [...]` line is the source of the error by removing that arg and attempting another `pulumi preview`: no panic occurs in that case.

**Comment by danielrbradley** [comment]
Yes, there seems to be an issue with the type - it should be `pulumi.Input<string>[]`. This can be worked-around by avoiding the type check:

```typescript
    variableGroups: [pulumiVariableGroup.id as any]
```
